export enum RoutesName {
    FRONT = "/",
    RESET_PASSWORD = "/admin/reset-password",
    CREATE_PASSWORD = "/admin/create-password",
    LOGIN = "/admin/login",
    HOME = "/admin",
    MEDIA = "/admin/media",
    POSTS = "/admin/posts",
    PAGES = "/admin/pages",
    PAGE = "/admin/pages/:pageId",
    CREATE_PAGE = "/admin/pages/create",
    APPEARANCE = "/admin/appearance",
    USERS = "/admin/users",
    SETTINGS = "/admin/settings",
}
