query clientPage($path: String!){
    clientPage(path: $path){
        item{
            description
            name
            path
            status{
                id
                name
                variant
            }
        }
    }
}