query pages($skip: Int, $take: Int){
    pages(skip: $skip, take: $take){
        count
        items{
            author{
                createdAt
                email
                id
                updatedAt
                username
            }
            createdAt
            description
            id
            name
            status{
                id
                name
            }
            updatedAt
        }
    }
}