query page($id: String, $path: String){
    page(id: $id, path: $path){
        item{
            author{
                createdAt
                email
                id
                updatedAt
                username
            }
            createdAt
            description
            id
            name
            path
            status{
                id
                name
                variant
            }
            updatedAt
        }
    }
}