query post($id: String!){
    post(id: $id){
        item{
            author{
                createdAt
                email
                id
                updatedAt
                username
            }
            createdAt
            description
            id
            name
            status{
                id
                name
                variant
            }
            updatedAt
        }
    }
}