query post($id: String!){
    post(id: $id){
        author{
            createdAt
            email
            firstName
            id
            lastName
            updatedAt
        }
        createdAt
        description
        id
        name
        status{
            id
            name
        }
        updatedAt
    }
}