query user($id: String!){
    user(id: $id){
        createdAt
        email
        firstName
        id
        lastName
        pages{
            author{
                createdAt
                email
                firstName
                id
                lastName
                pages{
                    createdAt
                    description
                    id
                    name
                    status{
                        id
                        name
                    }
                    updatedAt
                }
                posts{
                    author{
                        createdAt
                        email
                        firstName
                        id
                        lastName
                        updatedAt
                    }
                    createdAt
                    description
                    id
                    name
                    status{
                        id
                        name
                    }
                    updatedAt
                }
                updatedAt
            }
            createdAt
            description
            id
            name
            updatedAt
        }
        posts{
            createdAt
            description
            id
            name
            updatedAt
        }
        updatedAt
    }
}